#! Use https://carvel.dev/ytt/ to generate this template.
#! Either use the "Regenerate dependabot.yml" task in Codespaces, or run the following command:
#! > ytt -f .github/dependabot.template.yml > .github/dependabot.yml

#@ load("@ytt:struct", "struct")

#! Returns a dictionary that maps the major version of .NET Monitor
#! to the list of TFMs that the major version uses for build and test.
#@ def getTfms():
#@   return {
#@     "9": [ "net9.0", "net8.0", "net7.0", "net6.0" ],
#@     "8": [ "net8.0", "net7.0", "net6.0" ],
#@   }
#@ end

#! Returns an array of structs that represent a registration of the
#! target branch and which major version of .NET Monitor it builds.
#@ def getBranches():
#@   return [
#@     struct.encode({"name": "main", "majorVersion": "8"}),
#@     struct.encode({"name": "feature/9.x", "majorVersion": "9"}),
#@     struct.encode({"name": "release/8.0", "majorVersion": "8"}),
#@   ]
#@ end

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
#@ for branch in getBranches():
#@ commit_prefix = "[" + branch.name + "] "
  - package-ecosystem: "nuget"
    directory: "/eng/dependabot/independent"
    schedule:
      interval: "daily"
    target-branch: #@ branch.name
    ignore:
      - dependency-name: "Microsoft.Extensions.*"
        update-types:
        - "version-update:semver-major"
#@ if branch.majorVersion == "6":
      #! The IdentityModel libraries bring in System.Text.Json 8+ starting with 7.7.0.
      #! Keep the major and minor version pinned to avoid incompatible versions.
      - dependency-name: "Microsoft.IdentityModel.*"
        update-types:
        - "version-update:semver-major"
        - "version-update:semver-minor"
#@ end
      - dependency-name: "Moq"
    commit-message:
      prefix: #@ commit_prefix
    groups:
      azure-sdk-dependencies:
        patterns:
          - "Azure.Core"
          - "Azure.Identity"
          - "Azure.Storage.*"
      identity-dependencies:
        patterns:
          - "Microsoft.Identity.*"
          - "Microsoft.IdentityModel.*"
  - package-ecosystem: "nuget"
    directory: "/eng/dependabot/nuget.org"
    schedule:
      interval: "daily"
    target-branch: #@ branch.name
    commit-message:
      prefix: #@ commit_prefix
#@ for tfm in getTfms()[branch.majorVersion]:
  - package-ecosystem: "nuget"
    directory: #@ "/eng/dependabot/" + tfm
    schedule:
      interval: "daily"
    target-branch: #@ branch.name
    ignore:
      - dependency-name: "*"
        update-types:
        - "version-update:semver-major"
    commit-message:
      prefix: #@ commit_prefix
    groups:
      runtime-dependencies:
        patterns:
          - "Microsoft.Extensions.*"
          - "Microsoft.NETCore.DotNetHost"
          - "System.Text.Json"
#@ end
#@ end
