name: 'Check markdown links'
on:
  pull_request:
    paths: ['**.md']
    branches: ['main']

permissions:
  pull-requests: read

jobs:
  check-markdown-links:
    name: 'Check markdown links'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          persist-credentials: false

      - name: Check markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@5c5dfc0ac2e225883c0e5f03a85311ec2830d368
        with:
          config-file: .github/linters/check-markdown-links-config.json
          use-quiet-mode: 'yes'
          use-verbose-mode: 'no'
