name: 'Check markdown links'
on:
  pull_request:
    paths: ['**.md']
    branches: ['main']

permissions:
  pull-requests: read

jobs:
  check-markdown-links:
    name: 'Check markdown links'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
        with:
          persist-credentials: false

      - name: Check markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@3c3b66f1f7d0900e37b71eca45b63ea9eedfce31
        with:
          config-file: .github/linters/check-markdown-links-config.json
          use-quiet-mode: 'yes'
          use-verbose-mode: 'no'
