name: Scan For Learning Path Update Comments
on:
  pull_request_review_comment:
    types: [created]
  issue_comment:
    types: [created]

permissions:
  pull-requests: read
  issues: read

jobs:
  scan-for-learning-path-update-comments:
    if: startsWith(github.event.comment.body, 'ðŸ‘') && github.event.issue.title == '[BOT] Learning Path Update' && contains(fromJSON('["OWNER", "MEMBER", "COLLABORATOR"]'), github.event.comment.author_association)
    runs-on: ubuntu-latest
    steps:
      - name: Generate artifacts
        run: |
          mkdir -p ./learning-path-update
          echo -n "$COMMENT_AUTHOR" > ./learning-path-update/issue-user
          echo -n "$ISSUE_URL" > ./learning-path-update/issueUrl
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
          COMMENT_URL: ${{ github.event.comment.html_url }}
          COMMENT_AUTHOR: ${{ github.event.comment.user.login }}
          ISSUE_URL: ${{ github.event.issue.url }}

      - name: Upload artifacts
        uses: actions/upload-artifact@694cdabd8bdb0f10b2cea11669e1bf5453eed0a6
        with:
          name: learning-path-update
          path: learning-path-update/
