name: Scan For Learning Path Comments
on:
  pull_request_review_comment:
    types: [created]
  issue_comment:
    types: [created]

permissions:
  pull-requests: read
  issues: read

jobs:
  scan-for-learning-path-update-comments:
    if: github.event.comment.body == 'ðŸ‘' && github.event.issue.title == '[BOT] Learning Path Update' && contains(fromJSON('["OWNER", "MEMBER", "COLLABORATOR"]'), github.event.comment.author_association)
    runs-on: ubuntu-latest
    steps:
      - name: Generate artifacts
        run: |
          mkdir -p ./learning-path-update
          echo -n "#$ISSUE_NUMBER" > ./learning-path-update/issueNumber
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}

      - name: Upload artifacts
        uses: actions/upload-artifact@694cdabd8bdb0f10b2cea11669e1bf5453eed0a6
        with:
          name: learning-path-update
          path: learning-path-update/
