name: To Do Comments
on:
  pull_request_review_comment:
    types: [created]
  issue_comment:
    types: [created]
    
permissions:
  pull-requests: write
  issues: write

jobs:
  create-todo-issue:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.comment.body, '#TODO') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          trimmed_comment=$(echo "${{ github.event.comment.body }}" | sed 's/#TODO //g')
          gh issue create --label "todo" --assignee "${{ github.event.comment.user.login }}" --title "${ trimmed_comment }" --body "${{ github.event.comment.html_url }}"
        shell: bas
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
